# Generated by Django 4.0.3 on 2022-03-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyshoporderinfo',
            name='freight',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='运费'),
        ),
        migrations.AlterField(
            model_name='happyshoporderinfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='商品总金额'),
        ),
        migrations.AlterField(
            model_name='happyshopsku',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='成本价'),
        ),
        migrations.AlterField(
            model_name='happyshopsku',
            name='market_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='市场价/划线价'),
        ),
        migrations.AlterField(
            model_name='happyshopsku',
            name='sell_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='商品售价'),
        ),
    ]
