# Generated by Django 4.0.3 on 2022-03-31 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('happy_shop', '0002_alter_happyshoporderinfo_freight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='happyshopordersku',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='单价'),
        ),
    ]
