# Generated by Django 4.0.3 on 2022-04-07 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('happy_shop', '0004_happyshoprate'),
    ]

    operations = [
        migrations.AddField(
            model_name='happyshoprate',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
            preserve_default=False,
        ),
    ]
