# Generated by Django 4.1rc1 on 2022-08-26 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('happy_shop', '0007_happyshoprate_add_date_happyshoprate_is_del_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='happyshoprate',
            options={'ordering': ['-add_date']},
        ),
    ]
